sudo: required
services:
  - docker

before_install:
  - docker build -t akor2docker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akor2docker/docker-react npm run test -- --coverage